# Sourcing Data with an API (New York CitiBike and Weather Datasets)
## 01. Import Libraries
## 02. Create the List Comprehension
## 03. Get Weather data using NOAA's API
## 04. Wrangle Data
## 05. Merge Datasets

# 01. Import Libraries

In [1]:
import pandas as pd 
import numpy as np
import os 
import requests
import json
from datetime import datetime

# 02. Create the List Comprehension

In [2]:
folderpath = r"/Users/aya/Desktop/DataAnalytics/Data-Visualizations-with-Python/Achievement-2/CitiBike/Dataset"

In [3]:
#Create a list with all files in the folder using a list comperhension
filepaths  = [os.path.join(folderpath, name) for name in os.listdir(folderpath)]

In [4]:
filepaths

['/Users/aya/Desktop/DataAnalytics/Data-Visualizations-with-Python/Achievement-2/CitiBike/Dataset/JC-202203-citibike-tripdata.csv',
 '/Users/aya/Desktop/DataAnalytics/Data-Visualizations-with-Python/Achievement-2/CitiBike/Dataset/JC-202201-citibike-tripdata.csv',
 '/Users/aya/Desktop/DataAnalytics/Data-Visualizations-with-Python/Achievement-2/CitiBike/Dataset/JC-202209-citibike-tripdata.csv',
 '/Users/aya/Desktop/DataAnalytics/Data-Visualizations-with-Python/Achievement-2/CitiBike/Dataset/JC-202211-citibike-tripdata.csv',
 '/Users/aya/Desktop/DataAnalytics/Data-Visualizations-with-Python/Achievement-2/CitiBike/Dataset/JC-202207-citbike-tripdata.csv',
 '/Users/aya/Desktop/DataAnalytics/Data-Visualizations-with-Python/Achievement-2/CitiBike/Dataset/JC-202205-citibike-tripdata.csv',
 '/Users/aya/Desktop/DataAnalytics/Data-Visualizations-with-Python/Achievement-2/CitiBike/Dataset/JC-202202-citibike-tripdata.csv',
 '/Users/aya/Desktop/DataAnalytics/Data-Visualizations-with-Python/Achievement-2/CitiBike/Dataset/JC-202208-citibike-tripdata.csv',
 '/Users/aya/Desktop/DataAnalytics/Data-Visualizations-with-Python/Achievement-2/CitiBike/Dataset/JC-202206-citibike-tripdata.csv',
 '/Users/aya/Desktop/DataAnalytics/Data-Visualizations-with-Python/Achievement-2/CitiBike/Dataset/JC-202210-citibike-tripdata.csv',
 '/Users/aya/Desktop/DataAnalytics/Data-Visualizations-with-Python/Achievement-2/CitiBike/Dataset/JC-202204-citibike-tripdata.csv',
 '/Users/aya/Desktop/DataAnalytics/Data-Visualizations-with-Python/Achievement-2/CitiBike/Dataset/JC-202212-citibike-tripdata.csv']

In [5]:
#Read the files
df_read = [pd.read_csv(f) for f in filepaths]

In [6]:
#Concatenate/Join the files  --original indices of the DataFrames being concatenated will be ignored
df_concatenate = pd.concat(df_read, ignore_index=True)

In [7]:
#Check the dimensions
df_concatenate.shape

(895485, 13)

In [8]:
#Check the dataframe
df_concatenate.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,3255D3E3F33CDC45,classic_bike,2022-03-18 15:38:17,2022-03-18 15:45:34,Mama Johnson Field - 4 St & Jackson St,HB404,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,40.743140,-74.040041,40.736982,-74.027781,casual
1,17FA5604A37338F9,electric_bike,2022-03-04 16:44:48,2022-03-04 16:50:45,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
2,7DEC9ADDB8D6BBE1,electric_bike,2022-03-13 17:44:32,2022-03-13 17:54:44,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
3,9D69F74EEF231A2E,classic_bike,2022-03-13 15:33:47,2022-03-13 15:41:22,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
4,C84AE4A9D78A6347,classic_bike,2022-03-11 12:21:18,2022-03-11 12:33:24,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member

In [9]:
#Check the dataframe -CitiBike Dataset
df_concatenate.tail()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
895480,D438F1622839AC50,classic_bike,2022-12-06 15:43:38,2022-12-06 15:53:57,Dey St,JC065,Riverview Park,JC057,40.737828,-74.067083,40.744319,-74.043991,member
895481,747A63A8E782D171,electric_bike,2022-12-08 08:17:51,2022-12-08 08:23:33,9 St HBLR - Jackson St & 8 St,HB305,City Hall - Washington St & 1 St,HB105,40.747907,-74.038412,40.737360,-74.030970,casual
895482,AE090858CFDE6E82,electric_bike,2022-12-23 14:10:07,2022-12-23 14:14:18,Mama Johnson Field - 4 St & Jackson St,HB404,City Hall - Washington St & 1 St,HB105,40.743140,-74.040041,40.737360,-74.030970,member
895483,B3CC8E70AF4E259C,classic_bike,2022-12-02 04:43:25,2022-12-02 04:46:55,Mama Johnson Field - 4 St & Jackson St,HB404,City Hall - Washington St & 1 St,HB105,40.743135,-74.040080,40.737360,-74.030970,member
895484,176B601F21327350,classic_bike,2022-12-30 14:50:17,2022-12-30 14:55:37,14 St Ferry - 14 St & Shipyard Ln,HB202,City Hall - Washington St & 1 St,HB105,40.752747,-74.024035,40.737360,-74.030970,member

# Observations

+ Created a path to the directory (where the data files are).
+ Used list comprehension to create a list of all files in the directory.
+ Created a loop to read each file in the list (iterate through each file/ each list of elements), then passed
+ Concatenated/joined the dataframe (where the list is) by rows and assigned it to a new dataframe.

## 02. Get Weather data using NOAA's API

In [10]:
#Define the NOAA token 
Token = 'oiBcHAXgLpTiTqXWWOLPmYYTcdjQvIWs'

In [11]:
# Get the API (New York’s LaGuardia Airport Station ID >> GHCND:USW00014732)
api_request = requests.get('https://www.ncdc.noaa.gov/cdo-web/api/v2/data?datasetid=GHCND&datatypeid=TAVG&limit=1000&stationid=GHCND:USW00014732&startdate=2022-01-01&enddate=2022-12-31', headers={'token':Token})

In [12]:
#Load the api response as a json - Store the data in JASON format
json_data = json.loads(api_request.text)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [ ]:
json_data

## 03. Wrangle Data

In [ ]:
#Secure all items in the response that correspond to TAVG
#All the results from the JSON if the datatype = TAVG are being stored in the avg_temps list ** Ensure the query only returns average temperatures.
avg_temps = [item for item in json_data['results'] if item['datatype']=='TAVG']

In [ ]:
avg_temps

In [ ]:
# Get only the date field from all average temperature readings ** Only the dates from the avg_temps list are stored in the dates_temp list.
dates_temp = [item['date'] for item in avg_temps]

In [ ]:
dates_temp

In [ ]:
#Get the temperature from all average temperature readings ** Only the value column from the avg_temps list is stored in the temps list
temps = [item['value'] for item in avg_temps]

In [ ]:
temps

In [ ]:
#Create a dataframe to store the results
df_temp = pd.DataFrame()

In [ ]:
#Get only date and cast it to date time ** only the date is visible byremoving the time (hours, minutes, seconds) component 
df_temp['date'] = [datetime.strptime(json_data, "%Y-%m-%dT%H:%M:%S") for json_data in dates_temp]

In [ ]:
df_temp.head()

In [ ]:
#Convert temperature from tenths of Celsius to normal Celsius
df_temp['avgTemp'] = [float(v)/10.0 for v in temps]

In [ ]:
df_temp.tail(5)

In [ ]:
#Check the datatypes
df_temp.dtypes

In [ ]:
#Export the data
df_temp.to_csv('NY_weather_data.csv')

## 04. Merge Datasets

In [ ]:
df_concatenate.head()

In [ ]:
#Convert the started_at column to datetime format in the CitiBike dataset
df_concatenate['started_at'] = pd.to_datetime(df_concatenate['started_at'], dayfirst = True)

In [ ]:
#Split the date from the time
df_concatenate['date'] = pd.to_datetime(df_concatenate['started_at'], format='%Y-%m-%d').dt.date

In [ ]:
df_concatenate.head(3)

In [ ]:
df_concatenate['date'] = pd.to_datetime(df_concatenate['date'])

In [ ]:
df_concatenate.head()

In [ ]:
df_temp.head()

In [ ]:
%%time
df_merged = df_concatenate.merge(df_temp, how='left', on='date', indicator=True) ##Merge the datasets

In [ ]:
df_merged.head()

In [ ]:
#Check the merge flag
df_merged['_merge'].value_counts(dropna = False)

In [ ]:
#Check the dimensions
df_merged.shape

In [ ]:
#Export the dataset
df_merged.to_csv('CitiBikeW_data.csv')